/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.raw-table.conf 17436 2009-03-31 15:12:19Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "netCtrlDevMIB.h"

#define PHONE_NUM_LEN	20
/* column number definitions for table zhenRFenjTable */
#define COLUMN_ZJID		2
#define COLUMN_FENJID		3
#define COLUMN_FENJNUM		4

    /* Typical data structure for a row entry */
struct zhenRFenjTable_entry {
    /* Index values */
    long zjID;
	long old_zjID;
	
    /* Column values */
    long fenJID;
    long old_fenJID;
    char fenJNum[PHONE_NUM_LEN];
    size_t fenJNum_len;
    char old_fenJNum[PHONE_NUM_LEN];
    size_t old_fenJNum_len;

    int   valid;
};

/* create a new row in the table */
static struct zhenRFenjTable_entry *
zhenRFenjTable_createEntry( int dummy
                 , long  zjID
                ) {
    struct zhenRFenjTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct zhenRFenjTable_entry);
    if (!entry)
        return NULL;

    /* XXX - insert entry into local data structure */
    return entry;
}

/* remove a row from the table */
static void
zhenRFenjTable_removeEntry(struct zhenRFenjTable_entry *entry) {
    if (!entry)
        return;    /* Nothing to remove */

    /* XXX - remove entry from local data structure */

    if (entry)
        SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/** determine the appropriate row for an exact request */
static struct zhenRFenjTable_entry *
zhenRFenjTable_get_entry( netsnmp_variable_list *indexes ) {
    struct zhenRFenjTable_entry *row = NULL;

    /* XXX - Use the 'indexes' parameter to retrieve the data
       structure for the requested row, and return this. */
    return row;
}

/** determine the appropriate row for an fuzzy request */
static struct zhenRFenjTable_entry *
zhenRFenjTable_get_next_entry( netsnmp_handler_registration *reginfo,
                     netsnmp_request_info         *request,
                     int                           column,
                     netsnmp_variable_list        *indexes ) {
    struct zhenRFenjTable_entry *row = NULL;
    oid             build_space[MAX_OID_LEN];
    size_t          build_space_len = 0;
    size_t          index_oid_len = 0;

    /* XXX - Use the 'indexes' parameter to identify the
             next row in the table.... */

    /* XXX   .... update the 'indexes' parameter with the
             appropriate index values ... */

    /* ... and update the requested OID to match this instance */
    memcpy(build_space, reginfo->rootoid,   /* registered oid */
                        reginfo->rootoid_len * sizeof(oid));
    build_space_len = reginfo->rootoid_len;
    build_space[build_space_len++] = 1;  /* entry */
    build_space[build_space_len++] = column; /* column */
    build_oid_noalloc(build_space + build_space_len,
                      MAX_OID_LEN - build_space_len, &index_oid_len,
                      NULL, 0, indexes);
    snmp_set_var_objid(request->requestvb, build_space,
                       build_space_len + index_oid_len);

    /*  Finally, return the data structure for this row */
    return row;
}


/** handles requests for the zhenRFenjTable table */
static int
zhenRFenjTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct zhenRFenjTable_entry          *table_entry;
    int                         ret;

    switch (reqinfo->mode) {
        /*
         * Read-support
         */
    case MODE_GET:
	snmp_log(LOG_WARNING,"%s_%d \r\n", __func__, __LINE__);
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     zhenRFenjTable_get_entry( table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_ZJID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->zjID);
                break;
            case COLUMN_FENJID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->fenJID);
                break;
            case COLUMN_FENJNUM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->fenJNum,
                                          table_entry->fenJNum_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    case MODE_GETNEXT:
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     zhenRFenjTable_get_next_entry( reginfo, request,
                                   table_info->colnum, table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_ZJID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->zjID);
                break;
            case COLUMN_FENJID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->fenJID);
                break;
            case COLUMN_FENJNUM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->fenJNum,
                                          table_entry->fenJNum_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     zhenRFenjTable_get_entry( table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_ZJID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_FENJID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_FENJNUM:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->fenJNum));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     zhenRFenjTable_get_entry( table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_ZJID:
                table_entry->old_zjID = table_entry->zjID;
                table_entry->zjID     = *request->requestvb->val.integer;
                break;
            case COLUMN_FENJID:
                table_entry->old_fenJID = table_entry->fenJID;
                table_entry->fenJID     = *request->requestvb->val.integer;
                break;
            case COLUMN_FENJNUM:
                memcpy( table_entry->old_fenJNum,
                        table_entry->fenJNum,
                        sizeof(table_entry->fenJNum));
                table_entry->old_fenJNum_len =
                        table_entry->fenJNum_len;
                memset( table_entry->fenJNum, 0,
                        sizeof(table_entry->fenJNum));
                memcpy( table_entry->fenJNum,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->fenJNum_len =
                        request->requestvb->val_len;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     zhenRFenjTable_get_entry( table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_ZJID:
                table_entry->zjID     = table_entry->old_zjID;
                table_entry->old_zjID = 0;
                break;
            case COLUMN_FENJID:
                table_entry->fenJID     = table_entry->old_fenJID;
                table_entry->old_fenJID = 0;
                break;
            case COLUMN_FENJNUM:
                memcpy( table_entry->fenJNum,
                        table_entry->old_fenJNum,
                        sizeof(table_entry->fenJNum));
                memset( table_entry->old_fenJNum, 0,
                        sizeof(table_entry->fenJNum));
                table_entry->fenJNum_len =
                        table_entry->old_fenJNum_len;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the zhenRFenjTable table by defining its contents and how it's structured */
static void
initialize_table_zhenRFenjTable(void)
{
    const oid zhenRFenjTable_oid[] = {1,3,6,1,4,1,589,1,3,3};
    netsnmp_handler_registration    *reg;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "zhenRFenjTable",     zhenRFenjTable_handler,
              zhenRFenjTable_oid, OID_LENGTH(zhenRFenjTable_oid),
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: zjID */
                           0);

    table_info->min_column = COLUMN_ZJID;
    table_info->max_column = COLUMN_FENJNUM;

    netsnmp_register_table( reg, table_info );

    /* Initialise the contents of the table here */
}

/** Initializes the netCtrlDevMIB module */
void
init_netCtrlDevMIB(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_zhenRFenjTable();
}
