/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.raw-table.conf 17436 2009-03-31 15:12:19Z dts12 $
 */
#ifndef NETCTRLDEVMIB_H
#define NETCTRLDEVMIB_H

void init_netCtrlDevMIB(void);

#endif /* NETCTRLDEVMIB_H */
