/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef CONFERENCETABLE_H
#define CONFERENCETABLE_H

/* function declarations */
void init_conferenceTable(void);
void initialize_table_conferenceTable(void);
Netsnmp_Node_Handler conferenceTable_handler;
Netsnmp_First_Data_Point  conferenceTable_get_first_data_point;
Netsnmp_Next_Data_Point   conferenceTable_get_next_data_point;

/* column number definitions for table conferenceTable */
       #define COLUMN_CONFNUM		1
       #define COLUMN_PARTCNT		2
       #define COLUMN_PARTNUM0		3
       #define COLUMN_PARTNUM1		4
       #define COLUMN_PARTNUM2		5
       #define COLUMN_PARTNUM3		6
       #define COLUMN_PARTNUM4		7
       #define COLUMN_PARTNUM5		8
#endif /* CONFERENCETABLE_H */
