/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "conferenceTable.h"
#include "mgwParaAccess.h"
#include "osa.h"

/** Initializes the conferenceTable module */
void
init_conferenceTable(void)
{
	initConfTab();
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_conferenceTable();
}


/** Initialize the conferenceTable table by defining its contents and how it's structured */
void
initialize_table_conferenceTable(void)
{
    const oid conferenceTable_oid[] = {1,3,6,1,4,1,589,1,3,3};
    const size_t conferenceTable_oid_len   = OID_LENGTH(conferenceTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("conferenceTable:init", "initializing table conferenceTable\n"));

    reg = netsnmp_create_handler_registration(
              "conferenceTable",     conferenceTable_handler,
              conferenceTable_oid, conferenceTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_OCTET_STR,  /* index: confNum */
                           0);
    table_info->min_column = COLUMN_CONFNUM;
    table_info->max_column = COLUMN_PARTNUM5;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = conferenceTable_get_first_data_point;
    iinfo->get_next_data_point  = conferenceTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct conferenceTable_entry {
    /* Index values */
    char confNum[CONF_TAB_NAME_LEN];
	
    /* Column values */
   
    size_t confNum_len;
    char old_confNum[CONF_TAB_ITEM_LEN];
    size_t old_confNum_len;
    long partCnt;
    long old_partCnt;
    char partNum0[CONF_TAB_ITEM_LEN];
    size_t partNum0_len;
    char old_partNum0[CONF_TAB_ITEM_LEN];
    size_t old_partNum0_len;
    char partNum1[CONF_TAB_ITEM_LEN];
    size_t partNum1_len;
    char old_partNum1[CONF_TAB_ITEM_LEN];
    size_t old_partNum1_len;
    char partNum2[CONF_TAB_ITEM_LEN];
    size_t partNum2_len;
    char old_partNum2[CONF_TAB_ITEM_LEN];
    size_t old_partNum2_len;
    char partNum3[CONF_TAB_ITEM_LEN];
    size_t partNum3_len;
    char old_partNum3[CONF_TAB_ITEM_LEN];
    size_t old_partNum3_len;
    char partNum4[CONF_TAB_ITEM_LEN];
    size_t partNum4_len;
    char old_partNum4[CONF_TAB_ITEM_LEN];
    size_t old_partNum4_len;
    char partNum5[CONF_TAB_ITEM_LEN];
    size_t partNum5_len;
    char old_partNum5[CONF_TAB_ITEM_LEN];
    size_t old_partNum5_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct conferenceTable_entry *next;
};

struct conferenceTable_entry  *conferenceTable_head;

/* create a new row in the (unsorted) table */
struct conferenceTable_entry *
conferenceTable_createEntry(
                ) {
    struct conferenceTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct conferenceTable_entry);
    if (!entry)
        return NULL;
    memset(entry,0x00,sizeof(struct conferenceTable_entry));
    entry->next = conferenceTable_head;
    conferenceTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
conferenceTable_removeEntry( struct conferenceTable_entry *entry ) {
    struct conferenceTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = conferenceTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        conferenceTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


static void fillConfTabEntry(struct conferenceTable_entry *entry, confTab_type *item){
	int i =0;	
	char *pPartNum = NULL;
	if(!entry || !item){
		OSA_ERROR("Invalid Para");
		return;
	}
	//dispBuf(item,sizeof(confTab_type),__func__);
	bcd_to_string(item->bcdConfNum,entry->confNum,CONF_NAME_LEN);
	entry->confNum_len = strlen(entry->confNum);
	entry->partCnt = item->partCnt;
	
	bcd_to_string(item->bcdPartNum0,entry->partNum0,BCD_PHONE_NUM_LEN);
		entry->partNum0_len = strlen(entry->partNum0);

	
	bcd_to_string(item->bcdPartNum1,entry->partNum1,BCD_PHONE_NUM_LEN);
	entry->partNum1_len = strlen(entry->partNum1);

	bcd_to_string(item->bcdPartNum2,entry->partNum2,BCD_PHONE_NUM_LEN);
	entry->partNum2_len = strlen(entry->partNum2);

	bcd_to_string(item->bcdPartNum3,entry->partNum3,BCD_PHONE_NUM_LEN);
	entry->partNum3_len = strlen(entry->partNum3);

	bcd_to_string(item->bcdPartNum4,entry->partNum4,BCD_PHONE_NUM_LEN);
	entry->partNum4_len = strlen(entry->partNum4);

	bcd_to_string(item->bcdPartNum5,entry->partNum5,BCD_PHONE_NUM_LEN);
	entry->partNum5_len = strlen(entry->partNum5);

}

static void loadConfTab(){
	int itemCnt = -1, i;
	confTab_type *tab = NULL;
	struct conferenceTable_entry *entry = NULL;
	tab = getConfTab(&itemCnt);
	if(!tab || itemCnt <=0){
		OSA_ERROR("Can't load Conf Table");
		return;
	}
	if(conferenceTable_head == NULL){
		for(i = 0; i < itemCnt; i++){
			conferenceTable_createEntry();
		}
	}	
	entry = conferenceTable_head;
	i = 0;
	while(entry){
		fillConfTabEntry(entry,&tab[i]);
		i++;
		entry = entry->next;
	}
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
conferenceTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    loadConfTab();

    *my_loop_context = conferenceTable_head;
    return conferenceTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
conferenceTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct conferenceTable_entry *entry = (struct conferenceTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_value( idx, entry->confNum, sizeof(entry->confNum) );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the conferenceTable table */
int
conferenceTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct conferenceTable_entry          *table_entry;
    int ret;
    DEBUGMSGTL(("conferenceTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct conferenceTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CONFNUM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->confNum,
                                          table_entry->confNum_len);
                break;
            case COLUMN_PARTCNT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->partCnt);
                break;
            case COLUMN_PARTNUM0:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->partNum0,
                                          table_entry->partNum0_len);
                break;
            case COLUMN_PARTNUM1:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->partNum1,
                                          table_entry->partNum1_len);
                break;
            case COLUMN_PARTNUM2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->partNum2,
                                          table_entry->partNum2_len);
                break;
            case COLUMN_PARTNUM3:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->partNum3,
                                          table_entry->partNum3_len);
                break;
            case COLUMN_PARTNUM4:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->partNum4,
                                          table_entry->partNum4_len);
                break;
            case COLUMN_PARTNUM5:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->partNum5,
                                          table_entry->partNum5_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct conferenceTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CONFNUM:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->confNum));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PARTCNT:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PARTNUM0:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->partNum0));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PARTNUM1:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->partNum1));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PARTNUM2:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->partNum2));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PARTNUM3:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->partNum3));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PARTNUM4:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->partNum4));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PARTNUM5:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->partNum5));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct conferenceTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CONFNUM:
                memcpy( table_entry->old_confNum,
                        table_entry->confNum,
                        sizeof(table_entry->confNum));
                table_entry->old_confNum_len =
                        table_entry->confNum_len;
                memset( table_entry->confNum, 0,
                        sizeof(table_entry->confNum));
                memcpy( table_entry->confNum,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->confNum_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_PARTCNT:
                table_entry->old_partCnt = table_entry->partCnt;
                table_entry->partCnt     = *request->requestvb->val.integer;
                break;
            case COLUMN_PARTNUM0:
                memcpy( table_entry->old_partNum0,
                        table_entry->partNum0,
                        sizeof(table_entry->partNum0));
                table_entry->old_partNum0_len =
                        table_entry->partNum0_len;
                memset( table_entry->partNum0, 0,
                        sizeof(table_entry->partNum0));
                memcpy( table_entry->partNum0,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->partNum0_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_PARTNUM1:
                memcpy( table_entry->old_partNum1,
                        table_entry->partNum1,
                        sizeof(table_entry->partNum1));
                table_entry->old_partNum1_len =
                        table_entry->partNum1_len;
                memset( table_entry->partNum1, 0,
                        sizeof(table_entry->partNum1));
                memcpy( table_entry->partNum1,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->partNum1_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_PARTNUM2:
                memcpy( table_entry->old_partNum2,
                        table_entry->partNum2,
                        sizeof(table_entry->partNum2));
                table_entry->old_partNum2_len =
                        table_entry->partNum2_len;
                memset( table_entry->partNum2, 0,
                        sizeof(table_entry->partNum2));
                memcpy( table_entry->partNum2,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->partNum2_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_PARTNUM3:
                memcpy( table_entry->old_partNum3,
                        table_entry->partNum3,
                        sizeof(table_entry->partNum3));
                table_entry->old_partNum3_len =
                        table_entry->partNum3_len;
                memset( table_entry->partNum3, 0,
                        sizeof(table_entry->partNum3));
                memcpy( table_entry->partNum3,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->partNum3_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_PARTNUM4:
                memcpy( table_entry->old_partNum4,
                        table_entry->partNum4,
                        sizeof(table_entry->partNum4));
                table_entry->old_partNum4_len =
                        table_entry->partNum4_len;
                memset( table_entry->partNum4, 0,
                        sizeof(table_entry->partNum4));
                memcpy( table_entry->partNum4,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->partNum4_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_PARTNUM5:
                memcpy( table_entry->old_partNum5,
                        table_entry->partNum5,
                        sizeof(table_entry->partNum5));
                table_entry->old_partNum5_len =
                        table_entry->partNum5_len;
                memset( table_entry->partNum5, 0,
                        sizeof(table_entry->partNum5));
                memcpy( table_entry->partNum5,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->partNum5_len =
                        request->requestvb->val_len;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct conferenceTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CONFNUM:
                memcpy( table_entry->confNum,
                        table_entry->old_confNum,
                        sizeof(table_entry->confNum));
                memset( table_entry->old_confNum, 0,
                        sizeof(table_entry->confNum));
                table_entry->confNum_len =
                        table_entry->old_confNum_len;
                break;
            case COLUMN_PARTCNT:
                table_entry->partCnt     = table_entry->old_partCnt;
                table_entry->old_partCnt = 0;
                break;
            case COLUMN_PARTNUM0:
                memcpy( table_entry->partNum0,
                        table_entry->old_partNum0,
                        sizeof(table_entry->partNum0));
                memset( table_entry->old_partNum0, 0,
                        sizeof(table_entry->partNum0));
                table_entry->partNum0_len =
                        table_entry->old_partNum0_len;
                break;
            case COLUMN_PARTNUM1:
                memcpy( table_entry->partNum1,
                        table_entry->old_partNum1,
                        sizeof(table_entry->partNum1));
                memset( table_entry->old_partNum1, 0,
                        sizeof(table_entry->partNum1));
                table_entry->partNum1_len =
                        table_entry->old_partNum1_len;
                break;
            case COLUMN_PARTNUM2:
                memcpy( table_entry->partNum2,
                        table_entry->old_partNum2,
                        sizeof(table_entry->partNum2));
                memset( table_entry->old_partNum2, 0,
                        sizeof(table_entry->partNum2));
                table_entry->partNum2_len =
                        table_entry->old_partNum2_len;
                break;
            case COLUMN_PARTNUM3:
                memcpy( table_entry->partNum3,
                        table_entry->old_partNum3,
                        sizeof(table_entry->partNum3));
                memset( table_entry->old_partNum3, 0,
                        sizeof(table_entry->partNum3));
                table_entry->partNum3_len =
                        table_entry->old_partNum3_len;
                break;
            case COLUMN_PARTNUM4:
                memcpy( table_entry->partNum4,
                        table_entry->old_partNum4,
                        sizeof(table_entry->partNum4));
                memset( table_entry->old_partNum4, 0,
                        sizeof(table_entry->partNum4));
                table_entry->partNum4_len =
                        table_entry->old_partNum4_len;
                break;
            case COLUMN_PARTNUM5:
                memcpy( table_entry->partNum5,
                        table_entry->old_partNum5,
                        sizeof(table_entry->partNum5));
                memset( table_entry->old_partNum5, 0,
                        sizeof(table_entry->partNum5));
                table_entry->partNum5_len =
                        table_entry->old_partNum5_len;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
