/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef MEDIAGW_H
#define MEDIAGW_H

/* function declarations */
void init_mediaGW(void);
Netsnmp_Node_Handler handle_workMode;
Netsnmp_Node_Handler handle_gPortMode;

#endif /* MEDIAGW_H */
