/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ZHANSNET_H
#define ZHANSNET_H

/* function declarations */
void init_zhanSNet(void);
Netsnmp_Node_Handler handle_mode;
Netsnmp_Node_Handler handle_devSeq;
Netsnmp_Node_Handler handle_armyNum;
Netsnmp_Node_Handler handle_phoneLen;
Netsnmp_Node_Handler handle_audioCodec;
Netsnmp_Node_Handler handle_asNum;

#endif /* ZHANSNET_H */
