/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "zhenRFenjTable.h"
#include "zhenRFenjTableAccess.h"
#include "osa_debug.h"
#include "public.h"

/** Initializes the zhenRFenjTable module */
void
init_zhenRFenjTable(void)
{
    OSA_DBG_MSGX(" ");
    initZrfjTab();
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_zhenRFenjTable();
}


/** Initialize the zhenRFenjTable table by defining its contents and how it's structured */
void
initialize_table_zhenRFenjTable(void)
{
    const oid zhenRFenjTable_oid[] = {1,3,6,1,4,1,589,1,3,2};
    const size_t zhenRFenjTable_oid_len   = OID_LENGTH(zhenRFenjTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("zhenRFenjTable:init", "initializing table zhenRFenjTable\n"));

    reg = netsnmp_create_handler_registration(
              "zhenRFenjTable",     zhenRFenjTable_handler,
              zhenRFenjTable_oid, zhenRFenjTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: zjID */
                           0);
    table_info->min_column = COLUMN_ZJID;
    table_info->max_column = COLUMN_FENJNUM;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = zhenRFenjTable_get_first_data_point;
    iinfo->get_next_data_point  = zhenRFenjTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct zhenRFenjTable_entry {
    /* Index values */
    long zjID;

    /* Column values */
    long old_zjID;
    long fenJID;
    long old_fenJID;
    char fenJNum[PHONE_NUM_LEN];
    size_t fenJNum_len;
    char old_fenJNum[PHONE_NUM_LEN];
    size_t old_fenJNum_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct zhenRFenjTable_entry *next;
};

struct zhenRFenjTable_entry  *zhenRFenjTable_head;

/* create a new row in the (unsorted) table */
struct zhenRFenjTable_entry *
zhenRFenjTable_createEntry(
                 long  zjID
                ) {
    struct zhenRFenjTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct zhenRFenjTable_entry);
    if (!entry)
        return NULL;

   memset(entry,0x00,sizeof(struct zhenRFenjTable_entry));
    entry->zjID = zjID;
    entry->next = zhenRFenjTable_head;
    zhenRFenjTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
zhenRFenjTable_removeEntry( struct zhenRFenjTable_entry *entry ) {
    struct zhenRFenjTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = zhenRFenjTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        zhenRFenjTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

static void fillZrfnEntry(struct zhenRFenjTable_entry *entry, zhenRFJTab_type *item){
	if(!entry || !item){
		OSA_ERROR("Invalid Para");
		return;
	}
	entry->zjID = item->zjID;
	entry->fenJID = item->fenJID;
	bcd_to_string(item->bcdFenJNum,entry->fenJNum,BCD_PHONE_NUM_LEN);
	entry->fenJNum_len = strlen(entry->fenJNum);
	OSA_DBG_MSGX("Str=%s",entry->fenJNum);
}

static void loadZrfjTab(){
	int itemCnt = -1, i;
	zhenRFJTab_type *tab = NULL;
	struct zhenRFenjTable_entry *entry = NULL;


	
	tab = getGZRFJTab(&itemCnt);
	if(!tab || itemCnt <=0){
		OSA_ERROR("Can't load zhenRu FenJi Table");
		return;
	}
	
	if(zhenRFenjTable_head == NULL){
		for(i = 0; i < itemCnt; i++){
			zhenRFenjTable_createEntry(tab[i].zjID);
		}
	}

	
	entry = zhenRFenjTable_head;
	i = 0;
	while(entry){
		fillZrfnEntry(entry,&tab[i]);
		i++;
		entry = entry->next;
	}
	
	
	
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
zhenRFenjTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
	loadZrfjTab();
    *my_loop_context = zhenRFenjTable_head;
    return zhenRFenjTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
zhenRFenjTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct zhenRFenjTable_entry *entry = (struct zhenRFenjTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->zjID );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the zhenRFenjTable table */
int
zhenRFenjTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    int ret;
    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct zhenRFenjTable_entry          *table_entry;

    DEBUGMSGTL(("zhenRFenjTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zhenRFenjTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ZJID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->zjID);
                break;
            case COLUMN_FENJID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->fenJID);
                break;
            case COLUMN_FENJNUM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->fenJNum,
                                          table_entry->fenJNum_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zhenRFenjTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ZJID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_FENJID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_FENJNUM:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->fenJNum));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zhenRFenjTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ZJID:
                table_entry->old_zjID = table_entry->zjID;
                table_entry->zjID     = *request->requestvb->val.integer;
                break;
            case COLUMN_FENJID:
                table_entry->old_fenJID = table_entry->fenJID;
                table_entry->fenJID     = *request->requestvb->val.integer;
                break;
            case COLUMN_FENJNUM:
                memcpy( table_entry->old_fenJNum,
                        table_entry->fenJNum,
                        sizeof(table_entry->fenJNum));
                table_entry->old_fenJNum_len =
                        table_entry->fenJNum_len;
                memset( table_entry->fenJNum, 0,
                        sizeof(table_entry->fenJNum));
                memcpy( table_entry->fenJNum,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->fenJNum_len =
                        request->requestvb->val_len;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zhenRFenjTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ZJID:
                table_entry->zjID     = table_entry->old_zjID;
                table_entry->old_zjID = 0;
                break;
            case COLUMN_FENJID:
                table_entry->fenJID     = table_entry->old_fenJID;
                table_entry->old_fenJID = 0;
                break;
            case COLUMN_FENJNUM:
                memcpy( table_entry->fenJNum,
                        table_entry->old_fenJNum,
                        sizeof(table_entry->fenJNum));
                memset( table_entry->old_fenJNum, 0,
                        sizeof(table_entry->fenJNum));
                table_entry->fenJNum_len =
                        table_entry->old_fenJNum_len;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
