/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef ZWCONFTABLE_H
#define ZWCONFTABLE_H

/* function declarations */
void init_zwConfTable(void);
void initialize_table_zwConfTable(void);
Netsnmp_Node_Handler zwConfTable_handler;
Netsnmp_First_Data_Point  zwConfTable_get_first_data_point;
Netsnmp_Next_Data_Point   zwConfTable_get_next_data_point;

/* column number definitions for table zwConfTable */
       #define COLUMN_ZWCONFNUM		1
       #define COLUMN_ZWPARTCNT		2
       #define COLUMN_ZWPARTNUM0		3
       #define COLUMN_ZWPARTNUM1		4
       #define COLUMN_ZWPARTNUM2		5
       #define COLUMN_ZWPARTNUM3		6
       #define COLUMN_ZWPARTNUM4		7
       #define COLUMN_ZWPARTNUM5		9
       #define COLUMN_ZWPARTNUM6		10
       #define COLUMN_ZWPARTNUM7		11
       #define COLUMN_ZWPARTNUM8		12
       #define COLUMN_ZWPARTNUM9		13
       #define COLUMN_ZWPARTNUM10		14
       #define COLUMN_ZWPARTNUM11		15
       #define COLUMN_ZWPARTNUM12		16
       #define COLUMN_ZWPARTNUM13		17
       #define COLUMN_ZWPARTNUM14		18
       #define COLUMN_ZWPARTNUM15		19
#endif /* ZWCONFTABLE_H */
