/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "zwConfTable.h"
#include "zwParaAccess.h"
#include "osa_debug.h"

/** Initializes the zwConfTable module */
void
init_zwConfTable(void)
{
	initZwConfTab();

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_zwConfTable();
}

/** Initialize the zwConfTable table by defining its contents and how it's structured */
void
initialize_table_zwConfTable(void)
{
    const oid zwConfTable_oid[] = {1,3,6,1,4,1,589,1,2,3};
    const size_t zwConfTable_oid_len   = OID_LENGTH(zwConfTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("zwConfTable:init", "initializing table zwConfTable\n"));

    reg = netsnmp_create_handler_registration(
              "zwConfTable",     zwConfTable_handler,
              zwConfTable_oid, zwConfTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_OCTET_STR,  /* index: zwConfNum */
                           0);
    table_info->min_column = COLUMN_ZWCONFNUM;
    table_info->max_column = COLUMN_ZWPARTNUM15;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = zwConfTable_get_first_data_point;
    iinfo->get_next_data_point  = zwConfTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct zwConfTable_entry {
    /* Index values */
    char zwConfNum[CONF_NUM_LEN];
    size_t zwConfNum_len;

    /* Column values */
    //char zwConfNum[NNN];
    //size_t zwConfNum_len;
    char old_zwConfNum[CONF_NUM_LEN];
    size_t old_zwConfNum_len;
    long zwPartCnt;
    long old_zwPartCnt;
    char zwPartNum0[CONF_PART_NUM_LEN];
    size_t zwPartNum0_len;
    char old_zwPartNum0[CONF_PART_NUM_LEN];
    size_t old_zwPartNum0_len;
    char zwPartNum1[CONF_PART_NUM_LEN];
    size_t zwPartNum1_len;
    char old_zwPartNum1[CONF_PART_NUM_LEN];
    size_t old_zwPartNum1_len;
    char zwPartNum2[CONF_PART_NUM_LEN];
    size_t zwPartNum2_len;
    char old_zwPartNum2[CONF_PART_NUM_LEN];
    size_t old_zwPartNum2_len;
    char zwPartNum3[CONF_PART_NUM_LEN];
    size_t zwPartNum3_len;
    char old_zwPartNum3[CONF_PART_NUM_LEN];
    size_t old_zwPartNum3_len;
    char zwPartNum4[CONF_PART_NUM_LEN];
    size_t zwPartNum4_len;
    char old_zwPartNum4[CONF_PART_NUM_LEN];
    size_t old_zwPartNum4_len;
    char zwPartNum5[CONF_PART_NUM_LEN];
    size_t zwPartNum5_len;
    char old_zwPartNum5[CONF_PART_NUM_LEN];
    size_t old_zwPartNum5_len;
    char zwPartNum6[CONF_PART_NUM_LEN];
    size_t zwPartNum6_len;
    char old_zwPartNum6[CONF_PART_NUM_LEN];
    size_t old_zwPartNum6_len;
    char zwPartNum7[CONF_PART_NUM_LEN];
    size_t zwPartNum7_len;
    char old_zwPartNum7[CONF_PART_NUM_LEN];
    size_t old_zwPartNum7_len;
    char zwPartNum8[CONF_PART_NUM_LEN];
    size_t zwPartNum8_len;
    char old_zwPartNum8[CONF_PART_NUM_LEN];
    size_t old_zwPartNum8_len;
    char zwPartNum9[CONF_PART_NUM_LEN];
    size_t zwPartNum9_len;
    char old_zwPartNum9[CONF_PART_NUM_LEN];
    size_t old_zwPartNum9_len;
    char zwPartNum10[CONF_PART_NUM_LEN];
    size_t zwPartNum10_len;
    char old_zwPartNum10[CONF_PART_NUM_LEN];
    size_t old_zwPartNum10_len;
    char zwPartNum11[CONF_PART_NUM_LEN];
    size_t zwPartNum11_len;
    char old_zwPartNum11[CONF_PART_NUM_LEN];
    size_t old_zwPartNum11_len;
    char zwPartNum12[CONF_PART_NUM_LEN];
    size_t zwPartNum12_len;
    char old_zwPartNum12[CONF_PART_NUM_LEN];
    size_t old_zwPartNum12_len;
    char zwPartNum13[CONF_PART_NUM_LEN];
    size_t zwPartNum13_len;
    char old_zwPartNum13[CONF_PART_NUM_LEN];
    size_t old_zwPartNum13_len;
    char zwPartNum14[CONF_PART_NUM_LEN];
    size_t zwPartNum14_len;
    char old_zwPartNum14[CONF_PART_NUM_LEN];
    size_t old_zwPartNum14_len;
    char zwPartNum15[CONF_PART_NUM_LEN];
    size_t zwPartNum15_len;
    char old_zwPartNum15[CONF_PART_NUM_LEN];
    size_t old_zwPartNum15_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct zwConfTable_entry *next;
};

struct zwConfTable_entry  *zwConfTable_head;

/* create a new row in the (unsorted) table */
struct zwConfTable_entry *
zwConfTable_createEntry(
                 char* zwConfNum,
                 size_t zwConfNum_len
                ) {
    struct zwConfTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct zwConfTable_entry);
    if (!entry)
        return NULL;

    memcpy(entry->zwConfNum, zwConfNum, zwConfNum_len);
    entry->zwConfNum_len = zwConfNum_len;
    entry->next = zwConfTable_head;
    zwConfTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
zwConfTable_removeEntry( struct zwConfTable_entry *entry ) {
    struct zwConfTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = zwConfTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        zwConfTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


static void fillZwConfTableEntry(struct zwConfTable_entry *entry, zwConf_type *item){
	int i;
	if(!entry || !item){
		OSA_ERROR("Invalid Para");
		return;
	}
	bcd_to_string(&item->confNum, entry->zwConfNum, BCD_CONF_NUM_LEN);
	entry->zwConfNum_len = BCD_CONF_NUM_LEN;
	entry->zwPartCnt = item->partCnt;

	bcd_to_string(item->partNum[0], entry->zwPartNum0, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum0_len = BCD_CONF_PART_NUM_LEN;
	
	bcd_to_string(item->partNum[1], entry->zwPartNum1, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum1_len = BCD_CONF_PART_NUM_LEN;
	
	bcd_to_string(item->partNum[2], entry->zwPartNum2, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum2_len = BCD_CONF_PART_NUM_LEN;
	
	bcd_to_string(item->partNum[3], entry->zwPartNum3, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum3_len = BCD_CONF_PART_NUM_LEN;

	bcd_to_string(item->partNum[4], entry->zwPartNum4, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum4_len = BCD_CONF_PART_NUM_LEN;
	
	bcd_to_string(item->partNum[5], entry->zwPartNum5, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum5_len = BCD_CONF_PART_NUM_LEN;
	
	bcd_to_string(item->partNum[6], entry->zwPartNum6, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum6_len = BCD_CONF_PART_NUM_LEN;
	
	bcd_to_string(item->partNum[7], entry->zwPartNum7, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum7_len = BCD_CONF_PART_NUM_LEN;	

	bcd_to_string(item->partNum[8], entry->zwPartNum8, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum8_len = BCD_CONF_PART_NUM_LEN;

	bcd_to_string(item->partNum[9], entry->zwPartNum9, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum9_len = BCD_CONF_PART_NUM_LEN;

	bcd_to_string(item->partNum[10], entry->zwPartNum10, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum10_len = BCD_CONF_PART_NUM_LEN;

	bcd_to_string(item->partNum[11], entry->zwPartNum11, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum11_len = BCD_CONF_PART_NUM_LEN;

	bcd_to_string(item->partNum[12], entry->zwPartNum12, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum12_len = BCD_CONF_PART_NUM_LEN;

	bcd_to_string(item->partNum[13], entry->zwPartNum13, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum13_len = BCD_CONF_PART_NUM_LEN;

	bcd_to_string(item->partNum[14], entry->zwPartNum14, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum14_len = BCD_CONF_PART_NUM_LEN;

	bcd_to_string(item->partNum[15], entry->zwPartNum15, BCD_CONF_PART_NUM_LEN);
	entry->zwPartNum15_len = BCD_CONF_PART_NUM_LEN;	
}

static void loadZwConfTable(){

	int itemCnt = -1, i;
	zwConf_type *tab = NULL;
	struct zwConfTable_entry *entry = NULL;
	char ConfNum[BCD_CONF_NUM_LEN];

	tab = getZwConfTab(&itemCnt);
	OSA_DBG_MSGX(" itemCnt=%d", itemCnt);
	if(!tab || itemCnt <=0){
		OSA_ERROR("Can't load ZW Conf Table");
		return;
	}

	if(zwConfTable_head == NULL){
		for(i = 0; i < itemCnt; i++){	
			bcd_to_string(&tab[i].confNum,ConfNum,BCD_CONF_NUM_LEN);
			zwConfTable_createEntry(ConfNum, BCD_CONF_NUM_LEN);
		}
	}	
	OSA_DBG_MSGX(" ");
	entry = zwConfTable_head;
	i = 0;
	while(entry){
		fillZwConfTableEntry(entry,&tab[i]);
		i++;
		entry = entry->next;
	}
}

static int needClear = 1;
static void clearTab() {
	struct zwConfTable_entry *entry = NULL;

	while (zwConfTable_head) {
		entry = zwConfTable_head->next;
		free(zwConfTable_head);
		zwConfTable_head = entry;
	}
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
zwConfTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
	OSA_DBG_MSGX(" ");

	if (needClear) //clear table at first
		clearTab();
	needClear = 0;
	
	loadZwConfTable();

    *my_loop_context = zwConfTable_head;
    return zwConfTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
zwConfTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct zwConfTable_entry *entry = (struct zwConfTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_value( idx, entry->zwConfNum, sizeof(entry->zwConfNum) );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the zwConfTable table */
int
zwConfTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct zwConfTable_entry          *table_entry;
	int ret;

    DEBUGMSGTL(("zwConfTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zwConfTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

			if ( !table_entry ) {
				needClear = 1; // this loop is end, need to clear table next time
				OSA_DBG_MSGX(" ");
			}
    
            switch (table_info->colnum) {
            case COLUMN_ZWCONFNUM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwConfNum,
                                          table_entry->zwConfNum_len);
                break;
            case COLUMN_ZWPARTCNT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->zwPartCnt);
                break;
            case COLUMN_ZWPARTNUM0:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum0,
                                          table_entry->zwPartNum0_len);
                break;
            case COLUMN_ZWPARTNUM1:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum1,
                                          table_entry->zwPartNum1_len);
                break;
            case COLUMN_ZWPARTNUM2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum2,
                                          table_entry->zwPartNum2_len);
                break;
            case COLUMN_ZWPARTNUM3:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum3,
                                          table_entry->zwPartNum3_len);
                break;
            case COLUMN_ZWPARTNUM4:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum4,
                                          table_entry->zwPartNum4_len);
                break;
            case COLUMN_ZWPARTNUM5:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum5,
                                          table_entry->zwPartNum5_len);
                break;
            case COLUMN_ZWPARTNUM6:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum6,
                                          table_entry->zwPartNum6_len);
                break;
            case COLUMN_ZWPARTNUM7:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum7,
                                          table_entry->zwPartNum7_len);
                break;
            case COLUMN_ZWPARTNUM8:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum8,
                                          table_entry->zwPartNum8_len);
                break;
            case COLUMN_ZWPARTNUM9:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum9,
                                          table_entry->zwPartNum9_len);
                break;
            case COLUMN_ZWPARTNUM10:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum10,
                                          table_entry->zwPartNum10_len);
                break;
            case COLUMN_ZWPARTNUM11:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum11,
                                          table_entry->zwPartNum11_len);
                break;
            case COLUMN_ZWPARTNUM12:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum12,
                                          table_entry->zwPartNum12_len);
                break;
            case COLUMN_ZWPARTNUM13:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum13,
                                          table_entry->zwPartNum13_len);
                break;
            case COLUMN_ZWPARTNUM14:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum14,
                                          table_entry->zwPartNum14_len);
                break;
            case COLUMN_ZWPARTNUM15:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->zwPartNum15,
                                          table_entry->zwPartNum15_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zwConfTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ZWCONFNUM:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwConfNum));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTCNT:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM0:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum0));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM1:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum1));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM2:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum2));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM3:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum3));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM4:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum4));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM5:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum5));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM6:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum6));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM7:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum7));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM8:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum8));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM9:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum9));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM10:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum10));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM11:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum11));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM12:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum12));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM13:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum13));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM14:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum14));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZWPARTNUM15:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->zwPartNum15));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zwConfTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ZWCONFNUM:
                memcpy( table_entry->old_zwConfNum,
                        table_entry->zwConfNum,
                        sizeof(table_entry->zwConfNum));
                table_entry->old_zwConfNum_len =
                        table_entry->zwConfNum_len;
                memset( table_entry->zwConfNum, 0,
                        sizeof(table_entry->zwConfNum));
                memcpy( table_entry->zwConfNum,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwConfNum_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTCNT:
                table_entry->old_zwPartCnt = table_entry->zwPartCnt;
                table_entry->zwPartCnt     = *request->requestvb->val.integer;
                break;
            case COLUMN_ZWPARTNUM0:
                memcpy( table_entry->old_zwPartNum0,
                        table_entry->zwPartNum0,
                        sizeof(table_entry->zwPartNum0));
                table_entry->old_zwPartNum0_len =
                        table_entry->zwPartNum0_len;
                memset( table_entry->zwPartNum0, 0,
                        sizeof(table_entry->zwPartNum0));
                memcpy( table_entry->zwPartNum0,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum0_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM1:
                memcpy( table_entry->old_zwPartNum1,
                        table_entry->zwPartNum1,
                        sizeof(table_entry->zwPartNum1));
                table_entry->old_zwPartNum1_len =
                        table_entry->zwPartNum1_len;
                memset( table_entry->zwPartNum1, 0,
                        sizeof(table_entry->zwPartNum1));
                memcpy( table_entry->zwPartNum1,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum1_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM2:
                memcpy( table_entry->old_zwPartNum2,
                        table_entry->zwPartNum2,
                        sizeof(table_entry->zwPartNum2));
                table_entry->old_zwPartNum2_len =
                        table_entry->zwPartNum2_len;
                memset( table_entry->zwPartNum2, 0,
                        sizeof(table_entry->zwPartNum2));
                memcpy( table_entry->zwPartNum2,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum2_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM3:
                memcpy( table_entry->old_zwPartNum3,
                        table_entry->zwPartNum3,
                        sizeof(table_entry->zwPartNum3));
                table_entry->old_zwPartNum3_len =
                        table_entry->zwPartNum3_len;
                memset( table_entry->zwPartNum3, 0,
                        sizeof(table_entry->zwPartNum3));
                memcpy( table_entry->zwPartNum3,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum3_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM4:
                memcpy( table_entry->old_zwPartNum4,
                        table_entry->zwPartNum4,
                        sizeof(table_entry->zwPartNum4));
                table_entry->old_zwPartNum4_len =
                        table_entry->zwPartNum4_len;
                memset( table_entry->zwPartNum4, 0,
                        sizeof(table_entry->zwPartNum4));
                memcpy( table_entry->zwPartNum4,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum4_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM5:
                memcpy( table_entry->old_zwPartNum5,
                        table_entry->zwPartNum5,
                        sizeof(table_entry->zwPartNum5));
                table_entry->old_zwPartNum5_len =
                        table_entry->zwPartNum5_len;
                memset( table_entry->zwPartNum5, 0,
                        sizeof(table_entry->zwPartNum5));
                memcpy( table_entry->zwPartNum5,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum5_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM6:
                memcpy( table_entry->old_zwPartNum6,
                        table_entry->zwPartNum6,
                        sizeof(table_entry->zwPartNum6));
                table_entry->old_zwPartNum6_len =
                        table_entry->zwPartNum6_len;
                memset( table_entry->zwPartNum6, 0,
                        sizeof(table_entry->zwPartNum6));
                memcpy( table_entry->zwPartNum6,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum6_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM7:
                memcpy( table_entry->old_zwPartNum7,
                        table_entry->zwPartNum7,
                        sizeof(table_entry->zwPartNum7));
                table_entry->old_zwPartNum7_len =
                        table_entry->zwPartNum7_len;
                memset( table_entry->zwPartNum7, 0,
                        sizeof(table_entry->zwPartNum7));
                memcpy( table_entry->zwPartNum7,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum7_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM8:
                memcpy( table_entry->old_zwPartNum8,
                        table_entry->zwPartNum8,
                        sizeof(table_entry->zwPartNum8));
                table_entry->old_zwPartNum8_len =
                        table_entry->zwPartNum8_len;
                memset( table_entry->zwPartNum8, 0,
                        sizeof(table_entry->zwPartNum8));
                memcpy( table_entry->zwPartNum8,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum8_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM9:
                memcpy( table_entry->old_zwPartNum9,
                        table_entry->zwPartNum9,
                        sizeof(table_entry->zwPartNum9));
                table_entry->old_zwPartNum9_len =
                        table_entry->zwPartNum9_len;
                memset( table_entry->zwPartNum9, 0,
                        sizeof(table_entry->zwPartNum9));
                memcpy( table_entry->zwPartNum9,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum9_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM10:
                memcpy( table_entry->old_zwPartNum10,
                        table_entry->zwPartNum10,
                        sizeof(table_entry->zwPartNum10));
                table_entry->old_zwPartNum10_len =
                        table_entry->zwPartNum10_len;
                memset( table_entry->zwPartNum10, 0,
                        sizeof(table_entry->zwPartNum10));
                memcpy( table_entry->zwPartNum10,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum10_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM11:
                memcpy( table_entry->old_zwPartNum11,
                        table_entry->zwPartNum11,
                        sizeof(table_entry->zwPartNum11));
                table_entry->old_zwPartNum11_len =
                        table_entry->zwPartNum11_len;
                memset( table_entry->zwPartNum11, 0,
                        sizeof(table_entry->zwPartNum11));
                memcpy( table_entry->zwPartNum11,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum11_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM12:
                memcpy( table_entry->old_zwPartNum12,
                        table_entry->zwPartNum12,
                        sizeof(table_entry->zwPartNum12));
                table_entry->old_zwPartNum12_len =
                        table_entry->zwPartNum12_len;
                memset( table_entry->zwPartNum12, 0,
                        sizeof(table_entry->zwPartNum12));
                memcpy( table_entry->zwPartNum12,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum12_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM13:
                memcpy( table_entry->old_zwPartNum13,
                        table_entry->zwPartNum13,
                        sizeof(table_entry->zwPartNum13));
                table_entry->old_zwPartNum13_len =
                        table_entry->zwPartNum13_len;
                memset( table_entry->zwPartNum13, 0,
                        sizeof(table_entry->zwPartNum13));
                memcpy( table_entry->zwPartNum13,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum13_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM14:
                memcpy( table_entry->old_zwPartNum14,
                        table_entry->zwPartNum14,
                        sizeof(table_entry->zwPartNum14));
                table_entry->old_zwPartNum14_len =
                        table_entry->zwPartNum14_len;
                memset( table_entry->zwPartNum14, 0,
                        sizeof(table_entry->zwPartNum14));
                memcpy( table_entry->zwPartNum14,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum14_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZWPARTNUM15:
                memcpy( table_entry->old_zwPartNum15,
                        table_entry->zwPartNum15,
                        sizeof(table_entry->zwPartNum15));
                table_entry->old_zwPartNum15_len =
                        table_entry->zwPartNum15_len;
                memset( table_entry->zwPartNum15, 0,
                        sizeof(table_entry->zwPartNum15));
                memcpy( table_entry->zwPartNum15,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->zwPartNum15_len =
                        request->requestvb->val_len;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zwConfTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ZWCONFNUM:
                memcpy( table_entry->zwConfNum,
                        table_entry->old_zwConfNum,
                        sizeof(table_entry->zwConfNum));
                memset( table_entry->old_zwConfNum, 0,
                        sizeof(table_entry->zwConfNum));
                table_entry->zwConfNum_len =
                        table_entry->old_zwConfNum_len;
                break;
            case COLUMN_ZWPARTCNT:
                table_entry->zwPartCnt     = table_entry->old_zwPartCnt;
                table_entry->old_zwPartCnt = 0;
                break;
            case COLUMN_ZWPARTNUM0:
                memcpy( table_entry->zwPartNum0,
                        table_entry->old_zwPartNum0,
                        sizeof(table_entry->zwPartNum0));
                memset( table_entry->old_zwPartNum0, 0,
                        sizeof(table_entry->zwPartNum0));
                table_entry->zwPartNum0_len =
                        table_entry->old_zwPartNum0_len;
                break;
            case COLUMN_ZWPARTNUM1:
                memcpy( table_entry->zwPartNum1,
                        table_entry->old_zwPartNum1,
                        sizeof(table_entry->zwPartNum1));
                memset( table_entry->old_zwPartNum1, 0,
                        sizeof(table_entry->zwPartNum1));
                table_entry->zwPartNum1_len =
                        table_entry->old_zwPartNum1_len;
                break;
            case COLUMN_ZWPARTNUM2:
                memcpy( table_entry->zwPartNum2,
                        table_entry->old_zwPartNum2,
                        sizeof(table_entry->zwPartNum2));
                memset( table_entry->old_zwPartNum2, 0,
                        sizeof(table_entry->zwPartNum2));
                table_entry->zwPartNum2_len =
                        table_entry->old_zwPartNum2_len;
                break;
            case COLUMN_ZWPARTNUM3:
                memcpy( table_entry->zwPartNum3,
                        table_entry->old_zwPartNum3,
                        sizeof(table_entry->zwPartNum3));
                memset( table_entry->old_zwPartNum3, 0,
                        sizeof(table_entry->zwPartNum3));
                table_entry->zwPartNum3_len =
                        table_entry->old_zwPartNum3_len;
                break;
            case COLUMN_ZWPARTNUM4:
                memcpy( table_entry->zwPartNum4,
                        table_entry->old_zwPartNum4,
                        sizeof(table_entry->zwPartNum4));
                memset( table_entry->old_zwPartNum4, 0,
                        sizeof(table_entry->zwPartNum4));
                table_entry->zwPartNum4_len =
                        table_entry->old_zwPartNum4_len;
                break;
            case COLUMN_ZWPARTNUM5:
                memcpy( table_entry->zwPartNum5,
                        table_entry->old_zwPartNum5,
                        sizeof(table_entry->zwPartNum5));
                memset( table_entry->old_zwPartNum5, 0,
                        sizeof(table_entry->zwPartNum5));
                table_entry->zwPartNum5_len =
                        table_entry->old_zwPartNum5_len;
                break;
            case COLUMN_ZWPARTNUM6:
                memcpy( table_entry->zwPartNum6,
                        table_entry->old_zwPartNum6,
                        sizeof(table_entry->zwPartNum6));
                memset( table_entry->old_zwPartNum6, 0,
                        sizeof(table_entry->zwPartNum6));
                table_entry->zwPartNum6_len =
                        table_entry->old_zwPartNum6_len;
                break;
            case COLUMN_ZWPARTNUM7:
                memcpy( table_entry->zwPartNum7,
                        table_entry->old_zwPartNum7,
                        sizeof(table_entry->zwPartNum7));
                memset( table_entry->old_zwPartNum7, 0,
                        sizeof(table_entry->zwPartNum7));
                table_entry->zwPartNum7_len =
                        table_entry->old_zwPartNum7_len;
                break;
            case COLUMN_ZWPARTNUM8:
                memcpy( table_entry->zwPartNum8,
                        table_entry->old_zwPartNum8,
                        sizeof(table_entry->zwPartNum8));
                memset( table_entry->old_zwPartNum8, 0,
                        sizeof(table_entry->zwPartNum8));
                table_entry->zwPartNum8_len =
                        table_entry->old_zwPartNum8_len;
                break;
            case COLUMN_ZWPARTNUM9:
                memcpy( table_entry->zwPartNum9,
                        table_entry->old_zwPartNum9,
                        sizeof(table_entry->zwPartNum9));
                memset( table_entry->old_zwPartNum9, 0,
                        sizeof(table_entry->zwPartNum9));
                table_entry->zwPartNum9_len =
                        table_entry->old_zwPartNum9_len;
                break;
            case COLUMN_ZWPARTNUM10:
                memcpy( table_entry->zwPartNum10,
                        table_entry->old_zwPartNum10,
                        sizeof(table_entry->zwPartNum10));
                memset( table_entry->old_zwPartNum10, 0,
                        sizeof(table_entry->zwPartNum10));
                table_entry->zwPartNum10_len =
                        table_entry->old_zwPartNum10_len;
                break;
            case COLUMN_ZWPARTNUM11:
                memcpy( table_entry->zwPartNum11,
                        table_entry->old_zwPartNum11,
                        sizeof(table_entry->zwPartNum11));
                memset( table_entry->old_zwPartNum11, 0,
                        sizeof(table_entry->zwPartNum11));
                table_entry->zwPartNum11_len =
                        table_entry->old_zwPartNum11_len;
                break;
            case COLUMN_ZWPARTNUM12:
                memcpy( table_entry->zwPartNum12,
                        table_entry->old_zwPartNum12,
                        sizeof(table_entry->zwPartNum12));
                memset( table_entry->old_zwPartNum12, 0,
                        sizeof(table_entry->zwPartNum12));
                table_entry->zwPartNum12_len =
                        table_entry->old_zwPartNum12_len;
                break;
            case COLUMN_ZWPARTNUM13:
                memcpy( table_entry->zwPartNum13,
                        table_entry->old_zwPartNum13,
                        sizeof(table_entry->zwPartNum13));
                memset( table_entry->old_zwPartNum13, 0,
                        sizeof(table_entry->zwPartNum13));
                table_entry->zwPartNum13_len =
                        table_entry->old_zwPartNum13_len;
                break;
            case COLUMN_ZWPARTNUM14:
                memcpy( table_entry->zwPartNum14,
                        table_entry->old_zwPartNum14,
                        sizeof(table_entry->zwPartNum14));
                memset( table_entry->old_zwPartNum14, 0,
                        sizeof(table_entry->zwPartNum14));
                table_entry->zwPartNum14_len =
                        table_entry->old_zwPartNum14_len;
                break;
            case COLUMN_ZWPARTNUM15:
                memcpy( table_entry->zwPartNum15,
                        table_entry->old_zwPartNum15,
                        sizeof(table_entry->zwPartNum15));
                memset( table_entry->old_zwPartNum15, 0,
                        sizeof(table_entry->zwPartNum15));
                table_entry->zwPartNum15_len =
                        table_entry->old_zwPartNum15_len;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
