/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef ZWUSRTABLE_H
#define ZWUSRTABLE_H

/* function declarations */
void init_zwUsrTable(void);
void initialize_table_zwUsrTable(void);
Netsnmp_Node_Handler zwUsrTable_handler;
Netsnmp_First_Data_Point  zwUsrTable_get_first_data_point;
Netsnmp_Next_Data_Point   zwUsrTable_get_next_data_point;



/* column number definitions for table zwUsrTable */
       #define COLUMN_CHANID		1
       #define COLUMN_USRNUMBER		2
       #define COLUMN_SECNUM		3
#endif /* ZWUSRTABLE_H */
