/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "zwZxTable.h"
#include "zwParaAccess.h"
#include "osa_debug.h"

/** Initializes the zwZxTable module */
void
init_zwZxTable(void)
{
	initZwZxTab();

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_zwZxTable();
}

/** Initialize the zwZxTable table by defining its contents and how it's structured */
void
initialize_table_zwZxTable(void)
{
    const oid zwZxTable_oid[] = {1,3,6,1,4,1,589,1,2,4};
    const size_t zwZxTable_oid_len   = OID_LENGTH(zwZxTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("zwZxTable:init", "initializing table zwZxTable\n"));

    reg = netsnmp_create_handler_registration(
              "zwZxTable",     zwZxTable_handler,
              zwZxTable_oid, zwZxTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: port */
                           0);
    table_info->min_column = COLUMN_PHONEID;
    table_info->max_column = COLUMN_ZXSTATUS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = zwZxTable_get_first_data_point;
    iinfo->get_next_data_point  = zwZxTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct zwZxTable_entry {
    /* Index values */
    //long port;

    /* Column values */
    long phoneID;
    long old_phoneID;
    long port;
    long old_port;
    char army[BCD_ARMY_NUM_LEN];
    size_t army_len;
    char old_army[BCD_ARMY_NUM_LEN];
    size_t old_army_len;
    char calleeNum[BCD_USR_NUM_LEN];
    size_t calleeNum_len;
    char old_calleeNum[BCD_USR_NUM_LEN];
    size_t old_calleeNum_len;
    long zxStatus;
    long old_zxStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct zwZxTable_entry *next;
};

struct zwZxTable_entry  *zwZxTable_head;

/* create a new row in the (unsorted) table */
struct zwZxTable_entry *
zwZxTable_createEntry(
                 long  port
                ) {
    struct zwZxTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct zwZxTable_entry);
    if (!entry)
        return NULL;

    memset(entry,0x00,sizeof(struct zwZxTable_entry));

    entry->port = port;
    entry->next = zwZxTable_head;
    zwZxTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
zwZxTable_removeEntry(struct zwZxTable_entry *entry ) {
    struct zwZxTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = zwZxTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        zwZxTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

static void fillZwZxEntry(struct zwZxTable_entry *entry, zwZx_type *item){
	if(!entry || !item){
		OSA_ERROR("Invalid Para");
		return;
	}

	entry->port = item->port;
	entry->phoneID = item->phoneId;
	entry->army_len = BCD_ARMY_NUM_LEN;
	bcd_to_string(&item->army, entry->army, (BCD_ARMY_NUM_LEN+1)/2);
	entry->calleeNum_len = BCD_USR_NUM_LEN;
	bcd_to_string(&item->calleeNum, entry->calleeNum, BCD_USR_NUM_LEN / 2);
	entry->zxStatus = item->zxStatus;
}

static void loadZwZxTab(){
	int itemCnt = -1, i;
	zwZx_type *tab = NULL;
	struct zwZxTable_entry *entry = NULL;

	tab = getZwZxTab(&itemCnt);
	OSA_DBG_MSGX(" itemCnt=%d", itemCnt);
	if(!tab || itemCnt <=0){
		OSA_ERROR("Can't load ZW zhuanxian Table");
		return;
	}

	if(zwZxTable_head == NULL){
		for(i = 0; i < itemCnt; i++){
			zwZxTable_createEntry(tab[i].port);
		}
	}	
	entry = zwZxTable_head;
	i = 0;
	while(entry){
		fillZwZxEntry(entry,&tab[i]);
		i++;
		entry = entry->next;
	}
}

static int needClear = 1;
static void clearTab() {
	struct zwZxTable_entry *entry = NULL;

	while (zwZxTable_head) {
		entry = zwZxTable_head->next;
		free(zwZxTable_head);
		zwZxTable_head = entry;
	}
}

	
/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
zwZxTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
	OSA_DBG_MSGX(" ");

	if (needClear) //clear table at first
		clearTab();
	needClear = 0;

	loadZwZxTab();

    *my_loop_context = zwZxTable_head;
    return zwZxTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
zwZxTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct zwZxTable_entry *entry = (struct zwZxTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->port );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the zwZxTable table */
int
zwZxTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct zwZxTable_entry          *table_entry;
	int ret;
	
    DEBUGMSGTL(("zwZxTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zwZxTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

			if ( !table_entry ) {
				needClear = 1; // this loop is end, need to clear table next time
				OSA_DBG_MSGX(" ");
			}
    
            switch (table_info->colnum) {
            case COLUMN_PHONEID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->phoneID);
                break;
            case COLUMN_PORT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->port);
                break;
            case COLUMN_ARMY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->army,
                                          table_entry->army_len);
                break;
            case COLUMN_CALLEENUM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->calleeNum,
                                          table_entry->calleeNum_len);
                break;
            case COLUMN_ZXSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->zxStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zwZxTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PHONEID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PORT:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ARMY:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->army));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_CALLEENUM:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->calleeNum));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ZXSTATUS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zwZxTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PHONEID:
                table_entry->old_phoneID = table_entry->phoneID;
                table_entry->phoneID     = *request->requestvb->val.integer;
                break;
            case COLUMN_PORT:
                table_entry->old_port = table_entry->port;
                table_entry->port     = *request->requestvb->val.integer;
                break;
            case COLUMN_ARMY:
                memcpy( table_entry->old_army,
                        table_entry->army,
                        sizeof(table_entry->army));
                table_entry->old_army_len =
                        table_entry->army_len;
                memset( table_entry->army, 0,
                        sizeof(table_entry->army));
                memcpy( table_entry->army,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->army_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_CALLEENUM:
                memcpy( table_entry->old_calleeNum,
                        table_entry->calleeNum,
                        sizeof(table_entry->calleeNum));
                table_entry->old_calleeNum_len =
                        table_entry->calleeNum_len;
                memset( table_entry->calleeNum, 0,
                        sizeof(table_entry->calleeNum));
                memcpy( table_entry->calleeNum,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->calleeNum_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_ZXSTATUS:
                table_entry->old_zxStatus = table_entry->zxStatus;
                table_entry->zxStatus     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct zwZxTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PHONEID:
                table_entry->phoneID     = table_entry->old_phoneID;
                table_entry->old_phoneID = 0;
                break;
            case COLUMN_PORT:
                table_entry->port     = table_entry->old_port;
                table_entry->old_port = 0;
                break;
            case COLUMN_ARMY:
                memcpy( table_entry->army,
                        table_entry->old_army,
                        sizeof(table_entry->army));
                memset( table_entry->old_army, 0,
                        sizeof(table_entry->army));
                table_entry->army_len =
                        table_entry->old_army_len;
                break;
            case COLUMN_CALLEENUM:
                memcpy( table_entry->calleeNum,
                        table_entry->old_calleeNum,
                        sizeof(table_entry->calleeNum));
                memset( table_entry->old_calleeNum, 0,
                        sizeof(table_entry->calleeNum));
                table_entry->calleeNum_len =
                        table_entry->old_calleeNum_len;
                break;
            case COLUMN_ZXSTATUS:
                table_entry->zxStatus     = table_entry->old_zxStatus;
                table_entry->old_zxStatus = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
