/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef ZWZXTABLE_H
#define ZWZXTABLE_H

/* function declarations */
void init_zwZxTable(void);
void initialize_table_zwZxTable(void);
Netsnmp_Node_Handler zwZxTable_handler;
Netsnmp_First_Data_Point  zwZxTable_get_first_data_point;
Netsnmp_Next_Data_Point   zwZxTable_get_next_data_point;

/* column number definitions for table zwZxTable */
       #define COLUMN_PHONEID		1
       #define COLUMN_PORT		2
       #define COLUMN_ARMY		3
       #define COLUMN_CALLEENUM		4
       #define COLUMN_ZXSTATUS		5
#endif /* ZWZXTABLE_H */
